version: "3.7"

services:
    pagina_gestao:
        container_name: pagina-symfony
        platform: linux/amd64
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - pagina_symfony_network  # Corrigido o nome da rede
    nginx:
        container_name: servidor-symfony-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8988:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - pagina_symfony_network  # Corrigido o nome da rede

networks:
    pagina_symfony_network:  # Corrigido o nome da rede
        driver: bridge
